package diseñadores.negocios.dto;

public enum Permiso {
  VENDER,
  VER_HISTORIAL_VENTAS,
  VER_EXISTENCIA_PRODUCTOS,
  CONSOLIDAR_INVENTARIO,
  ADMINISTRAR_PROVEEDORES,
  VER_ORDENES_COMPRA,
  ASOCIAR_PROVEEDOR_PRODUCTO
}
